React posters testing
ajs476/react-posters pull request #10
Opened 2018-06-15 14:44 UTC by ajs476

2018-06-15 17:13 UTC, ajs476 commented
the searchHistory test in commit 24e19c7 wasn't working like I thought it was. I ended up removing it in the final commit because it didn't work like it should have.

2018-06-18 14:07 UTC, lucas-aragno requested changes

2018-06-18 14:07 UTC, lucas-aragno commented on posters-project/src/App.js
> +    qhttp.read(`https://www.omdbapi.com/?apikey=fd86ad97&s=${searchTitle}`)
can you move `https://www.omdbapi.com/?apikey=fd86ad97&s=` to a constant? e.g `SEARCH_URL`

2018-06-18 14:07 UTC, lucas-aragno commented on posters-project/src/components/Poster/poster.test.js
> +it('renders without crashing', () => { // eslint-disable-line no-undef
since you added `jest` to your eslint configs do you still ned the comment?

2018-06-18 14:07 UTC, lucas-aragno commented on posters-project/src/components/PosterList/posterlist.test.js
> +it('renders without crashing', () => { // eslint-disable-line no-undef
ditto

2018-06-18 14:11 UTC, ajs476 commented on posters-project/src/App.js
> +    qhttp.read(`https://www.omdbapi.com/?apikey=fd86ad97&s=${searchTitle}`)
done

2018-06-18 14:11 UTC, ajs476 commented on posters-project/src/components/Poster/poster.test.js
> +it('renders without crashing', () => { // eslint-disable-line no-undef
true these are left over and unnecessary, done.

2018-06-18 14:12 UTC, ajs476 commented on posters-project/src/components/PosterList/posterlist.test.js
> +it('renders without crashing', () => { // eslint-disable-line no-undef
done!

2018-06-18 14:34 UTC, lucas-aragno approved these changes

2018-06-18 14:49 UTC, merged