React app components 2
ajs476/react-posters pull request #4
Opened 2018-06-11 21:55 UTC by ajs476

2018-06-11 22:03 UTC, lucas-aragno commented on posters-project/src/App.js
> +      <PosterList movieList={this.state.movies}/>
destructure this

2018-06-11 22:03 UTC, lucas-aragno commented on posters-project/src/components/PosterList.js
> +      movieList.map(({title, genre, posterImageURL, userImageURL}, i) =>
use `index` instead of `i`

2018-06-11 22:03 UTC, lucas-aragno commented on posters-project/src/components/SearchBar.js
> +          onChange={ (changeEvent) =>
change this to it's own function w/o the arrow

2018-06-11 22:03 UTC, lucas-aragno commented on posters-project/src/components/SearchBar.js
> +        <button className="movieSearchButton" onClick={() => this.searchOMDB(this.state.inputValue)}>Search</button>
destructure state

2018-06-12 17:02 UTC, ajs476 commented on posters-project/src/components/PosterList.js
> +      movieList.map(({title, genre, posterImageURL, userImageURL}, i) =>
done!

2018-06-12 17:04 UTC, ajs476 commented on posters-project/src/components/SearchBar.js
> +          onChange={ (changeEvent) =>
I got rid of the arrow function and am calling updateInputValue() now.

2018-06-12 17:06 UTC, ajs476 commented on posters-project/src/App.js
> +      <PosterList movieList={this.state.movies}/>
done

2018-06-12 17:06 UTC, ajs476 commented on posters-project/src/components/SearchBar.js
> +        <button className="movieSearchButton" onClick={() => this.searchOMDB(this.state.inputValue)}>Search</button>
done!

2018-06-12 17:08 UTC, ajs476 commented
The last commit is technically named incorrectly. It really is just destructuring the state you requested.

2018-06-12 17:13 UTC, lucas-aragno requested changes

2018-06-12 17:13 UTC, lucas-aragno commented on posters-project/src/components/SearchBar.js
> +      this.props.updateMovies({title, genre, posterImageURL, userImageURL});
maybe instead of declaring so many variables you can do 

this.props.updateMovies({
  title: omdbResult.Title
})


and so for it

2018-06-12 17:17 UTC, ajs476 commented on posters-project/src/components/SearchBar.js
> +      this.props.updateMovies({title, genre, posterImageURL, userImageURL});
on it! good call.

2018-06-12 17:21 UTC, ajs476 commented on posters-project/src/components/SearchBar.js
> +      this.props.updateMovies({title, genre, posterImageURL, userImageURL});
done!

2018-06-12 17:23 UTC, lucas-aragno approved these changes

2018-06-12 17:24 UTC, merged